name=input("What is your name: ")
age=int(input("What is your age: "))
class_studying=int(input("Which class do you read: "))
subject=input("What is your favourite subject: ")
games=input("What is your favourite game: ")
best_friend=input("Who is your best friend: ")
lives=input("Where do you live: ")
aim=input("What is your aim: ")
colour=input("What is your favourite colour: ")
num=input("What is your favourite number: ")
food=input("What is your favourite food: ")
print(name,"is",age,"years old and studies in class",class_studying,".","His favourite subject is",subject,".","He loves to play",games,"and his best friend is",best_friend,"and he lives in",lives,"His aim is to be",aim,".","His favourite colour is",colour,"and his favourite number is",num,"and favourite food is",food,".") 
